# Generated by Django 4.2.5 on 2024-05-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_products_product_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sales',
        ),
    ]
