# Generated by Django 4.2.5 on 2024-05-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
