# Generated by Django 4.2.5 on 2024-05-10 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_item',
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.IntegerField()),
                ('order_date', models.CharField(max_length=250)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_order_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.orders'),
            preserve_default=False,
        ),
    ]
