# Generated by Django 4.2.5 on 2024-05-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_invoice_invoice_item_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
