# Generated by Django 4.2.5 on 2024-05-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_invoice_invoice_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_item_total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
