# Generated by Django 4.2.5 on 2024-05-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_orders_order_item_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_order_number',
            field=models.IntegerField(),
        ),
    ]
