# Generated by Django 4.2.5 on 2024-05-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_invoice_invoice_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
    ]
