# Generated by Django 4.2.5 on 2024-05-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.FloatField(),
        ),
    ]
