# Generated by Django 4.2.5 on 2024-05-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_invoice_invoice_total_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=250)),
                ('ingredient_quantity', models.FloatField()),
                ('ingredient_unit', models.CharField(max_length=100)),
                ('ingredient_arrive_date', models.CharField(max_length=250)),
                ('ingredient_expiration_date', models.CharField(max_length=250)),
            ],
        ),
    ]
