# Generated by Django 4.2.5 on 2024-05-14 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Ingredients',
            fields=[
                ('product_ingredient', models.AutoField(primary_key=True, serialize=False)),
                ('product_ingredient_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredients')),
                ('product_ingredient_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
        ),
    ]
