# Generated by Django 4.2.5 on 2024-05-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_products_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_quantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
