# Generated by Django 4.2.5 on 2024-05-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_products_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_item_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
