# Generated by Django 4.2.5 on 2024-05-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_orders_order_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_quantity',
        ),
    ]
