# Generated by Django 4.2.5 on 2024-05-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_products_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_ingredients',
            name='product_ingredient_quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products_ingredients',
            name='product_ingredient_unit',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
